### ISSUE TITLE
How do you change the port the server runs on? 

### ISSUE THREAD

**Issue by ricotomo** [transparency-everywhere/position-api#5]
I have another process running on port 5000 which is causing an error when I start the server. How can I change the port the server runs on? 

I would guess it is by changing the "PORT=" value the in .env.template. However, doing so does not seem to affect the port. For example, I change the port to 5003 and restart the server. However, I then continue to receive the same error:
node:events:497
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1] 
[1] Error: listen EADDRINUSE: address already in use :::5000
[1]     at Server.setupListenHandle [as _listen2] (node:net:1872:16)
[1]     at listenInCluster (node:net:1920:12)
[1]     at Server.listen (node:net:2008:7)
[1]     at Function.listen (/Users/mwalther/Downloads/position-api-main/node_modules/express/lib/application.js:635:24)
[1]     at Server.init (/Users/mwalther/Downloads/position-api-main/dist/classes/server.js:27:18)
[1]     at new Server (/Users/mwalther/Downloads/position-api-main/dist/classes/server.js:14:14)
[1]     at Object.<anonymous> (/Users/mwalther/Downloads/position-api-main/dist/index.js:13:1)
[1]     at Module._compile (node:internal/modules/cjs/loader:1376:14)
[1]     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
[1]     at Module.load (node:internal/modules/cjs/loader:1207:32)
[1] Emitted 'error' event on Server instance at:
[1]     at emitErrorNT (node:net:1899:8)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
[1]   code: 'EADDRINUSE',
[1]   errno: -48,
[1]   syscall: 'listen',
[1]   address: '::',
[1]   port: 5000
[1] }
[1] 
[1] Node.js v21.2.0

**Comment by niczem** [comment]
Hi there,
the .env.template is only a template which is copied to the .env file.
You can simply update the port in the .env file
